#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
#sudo: false
sudo: required
group: edge

# build only on master branches
# commented as this prevents people from running builds on their forks:
# https://github.com/yiisoft/yii2/commit/bd87be990fa238c6d5e326d0a171f38d02dc253a
#branches:
#  only:
#    - master
#    - 2.1


#
# Test Matrix
#

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"

services:
  - memcached
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS


before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - mysql --version



script:
  # PHP tests
  - data/vendors/bin/phpunit --bootstrap data/vendors/autoload.php --testdox tests

