<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaa712040fb9446997fce28caea1536d8
{
    public static $files = array (
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
        'c65d09b6820da036953a371c8c73a9b1' => __DIR__ . '/..' . '/facebook/graph-sdk/src/Facebook/polyfills.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'V' => 
        array (
            'View\\' => 5,
        ),
        'T' => 
        array (
            'Twig\\' => 5,
            'Table\\' => 6,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\Filesystem\\' => 29,
            'Symfony\\Component\\DomCrawler\\' => 29,
            'Symfony\\Component\\Debug\\' => 24,
            'Symfony\\Component\\Console\\' => 26,
            'Symfony\\Component\\BrowserKit\\' => 29,
        ),
        'R' => 
        array (
            'Ramsey\\Uuid\\' => 12,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Cache\\' => 10,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
            'Model\\' => 6,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
            'Grpc\\' => 5,
            'Google\\Type\\' => 12,
            'Google\\Rpc\\' => 11,
            'Google\\Protobuf\\' => 16,
            'Google\\LongRunning\\' => 19,
            'Google\\Jison\\' => 13,
            'Google\\Iam\\' => 11,
            'Google\\Cloud\\Vision\\' => 20,
            'Google\\Cloud\\VideoIntelligence\\' => 31,
            'Google\\Cloud\\Utils\\' => 19,
            'Google\\Cloud\\Translate\\' => 23,
            'Google\\Cloud\\Trace\\' => 19,
            'Google\\Cloud\\TestUtils\\' => 23,
            'Google\\Cloud\\Storage\\' => 21,
            'Google\\Cloud\\Speech\\' => 20,
            'Google\\Cloud\\Spanner\\' => 21,
            'Google\\Cloud\\PubSub\\' => 20,
            'Google\\Cloud\\OsLogin\\' => 21,
            'Google\\Cloud\\Monitoring\\' => 24,
            'Google\\Cloud\\Logging\\' => 21,
            'Google\\Cloud\\Language\\' => 22,
            'Google\\Cloud\\Firestore\\' => 23,
            'Google\\Cloud\\ErrorReporting\\' => 28,
            'Google\\Cloud\\Dlp\\' => 17,
            'Google\\Cloud\\Debugger\\' => 22,
            'Google\\Cloud\\Datastore\\' => 23,
            'Google\\Cloud\\Dataproc\\' => 22,
            'Google\\Cloud\\Core\\' => 18,
            'Google\\Cloud\\Container\\' => 23,
            'Google\\Cloud\\Bigtable\\' => 22,
            'Google\\Cloud\\BigQuery\\DataTransfer\\' => 35,
            'Google\\Cloud\\BigQuery\\' => 22,
            'Google\\Cloud\\' => 13,
            'Google\\Auth\\' => 12,
            'Google\\Api\\' => 11,
            'Google\\ApiCore\\' => 15,
            'Google\\' => 7,
            'GPBMetadata\\Google\\Protobuf\\' => 28,
            'GPBMetadata\\Google\\' => 19,
            'GPBMetadata\\' => 12,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
            'Facebook\\' => 9,
        ),
        'C' => 
        array (
            'Controller\\' => 11,
            'Carbon\\Interfaces\\' => 18,
            'Carbon\\Helpers\\' => 15,
            'Carbon\\Error\\' => 13,
            'Carbon\\' => 7,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'View\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Application/View',
        ),
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Table\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Application/Table',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Symfony\\Component\\DomCrawler\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dom-crawler',
        ),
        'Symfony\\Component\\Debug\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/debug',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Symfony\\Component\\BrowserKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/browser-kit',
        ),
        'Ramsey\\Uuid\\' => 
        array (
            0 => __DIR__ . '/..' . '/ramsey/uuid/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Model\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Application/Model',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Grpc\\' => 
        array (
            0 => __DIR__ . '/..' . '/grpc/grpc/src/lib',
        ),
        'Google\\Type\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/Type',
        ),
        'Google\\Rpc\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/Rpc',
        ),
        'Google\\Protobuf\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/protobuf/php/src/Google/Protobuf',
        ),
        'Google\\LongRunning\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/LongRunning',
        ),
        'Google\\Jison\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/Jison',
        ),
        'Google\\Iam\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/Iam',
        ),
        'Google\\Cloud\\Vision\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Vision/src',
        ),
        'Google\\Cloud\\VideoIntelligence\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/VideoIntelligence/src',
        ),
        'Google\\Cloud\\Utils\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud-tools/src/Utils',
        ),
        'Google\\Cloud\\Translate\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Translate/src',
        ),
        'Google\\Cloud\\Trace\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Trace/src',
        ),
        'Google\\Cloud\\TestUtils\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud-tools/src/TestUtils',
        ),
        'Google\\Cloud\\Storage\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Storage/src',
        ),
        'Google\\Cloud\\Speech\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Speech/src',
        ),
        'Google\\Cloud\\Spanner\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Spanner/src',
        ),
        'Google\\Cloud\\PubSub\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/PubSub/src',
        ),
        'Google\\Cloud\\OsLogin\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/OsLogin/src',
        ),
        'Google\\Cloud\\Monitoring\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Monitoring/src',
        ),
        'Google\\Cloud\\Logging\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Logging/src',
        ),
        'Google\\Cloud\\Language\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Language/src',
        ),
        'Google\\Cloud\\Firestore\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Firestore/src',
        ),
        'Google\\Cloud\\ErrorReporting\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/ErrorReporting/src',
        ),
        'Google\\Cloud\\Dlp\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Dlp/src',
        ),
        'Google\\Cloud\\Debugger\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Debugger/src',
        ),
        'Google\\Cloud\\Datastore\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Datastore/src',
        ),
        'Google\\Cloud\\Dataproc\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Dataproc/src',
        ),
        'Google\\Cloud\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Core/src',
        ),
        'Google\\Cloud\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Container/src',
        ),
        'Google\\Cloud\\Bigtable\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/Bigtable/src',
        ),
        'Google\\Cloud\\BigQuery\\DataTransfer\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/BigQueryDataTransfer/src',
        ),
        'Google\\Cloud\\BigQuery\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/BigQuery/src',
        ),
        'Google\\Cloud\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/cloud/src',
            1 => __DIR__ . '/..' . '/google/gax/src/Cloud',
        ),
        'Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/auth/src',
        ),
        'Google\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/Api',
        ),
        'Google\\ApiCore\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/src/ApiCore',
        ),
        'Google\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/proto-client/src/Google',
        ),
        'GPBMetadata\\Google\\Protobuf\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/protobuf/php/src/GPBMetadata/Google/Protobuf',
        ),
        'GPBMetadata\\Google\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/gax/metadata',
        ),
        'GPBMetadata\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/proto-client/src/GPBMetadata',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'Facebook\\' => 
        array (
            0 => __DIR__ . '/..' . '/facebook/graph-sdk/src/Facebook',
        ),
        'Controller\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Application/Controller',
        ),
        'Carbon\\Interfaces\\' => 
        array (
            0 => __DIR__ . '/..' . '/richardtmiles/carbonphp/Interfaces',
        ),
        'Carbon\\Helpers\\' => 
        array (
            0 => __DIR__ . '/..' . '/richardtmiles/carbonphp/Helpers',
        ),
        'Carbon\\Error\\' => 
        array (
            0 => __DIR__ . '/..' . '/richardtmiles/carbonphp/Error',
        ),
        'Carbon\\' => 
        array (
            0 => __DIR__ . '/..' . '/richardtmiles/carbonphp/Structure',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Application',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'R' => 
        array (
            'Rize\\UriTemplate' => 
            array (
                0 => __DIR__ . '/..' . '/rize/uri-template/src',
            ),
        ),
        'M' => 
        array (
            'Mustache' => 
            array (
                0 => __DIR__ . '/..' . '/mustache/mustache/src',
            ),
        ),
        'G' => 
        array (
            'Google_Service_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient-services/src',
            ),
            'Google_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient/src',
            ),
        ),
    );

    public static $classMap = array (
        'Google_Service_Exception' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Exception.php',
        'Google_Service_Resource' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Resource.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaa712040fb9446997fce28caea1536d8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaa712040fb9446997fce28caea1536d8::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitaa712040fb9446997fce28caea1536d8::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitaa712040fb9446997fce28caea1536d8::$classMap;

        }, null, ClassLoader::class);
    }
}
